apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: analysis-service
  name: analysis-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: analysis-service
    spec:
      containers:
      - image: analysis-service
        name: analysis-service
        resources: {}
      restartPolicy: Always
status: {}
