apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: display-service
status:
  loadBalancer: {}
