apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: display-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: display-service
    spec:
      containers:
      - image: display-service
        name: display-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
