apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: display-service
  name: display-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: display-service
    spec:
      containers:
      - image: display-service
        name: display-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
